// ---------------------------------------------------------------------------
// Where the encrypted bytes live.
//
// Two drivers behind one interface. Local disk is for development only: on
// Render's free tier the filesystem is ephemeral and every ID would vanish on
// the next deploy (docs/TECH_STACK.md §2a), so production is R2.
//
// R2 is reached with aws4fetch (65KB) rather than the AWS SDK (3.3MB). It signs
// a request; that is all we need.
// ---------------------------------------------------------------------------
import { mkdir, writeFile, readFile, unlink } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { randomBytes } from "node:crypto";

/** An opaque key. Never the guest's name, the booking code, or anything guessable. */
export const newFileRef = () => `${new Date().toISOString().slice(0, 7)}/${randomBytes(16).toString("hex")}`;

function localStore({ dir }) {
  const root = resolve(dir);
  const pathFor = (ref) => {
    const full = resolve(root, ref);
    // A ref is generated by us, but check anyway: one traversal bug here writes
    // or reads anywhere on disk.
    if (!full.startsWith(root + "/")) throw new Error("refusing a file ref outside the upload directory");
    return full;
  };
  return {
    name: "local",
    async put(ref, bytes) {
      const full = pathFor(ref);
      await mkdir(dirname(full), { recursive: true });
      await writeFile(full, bytes, { mode: 0o600 });
      return { ref, bytes: bytes.length };
    },
    async get(ref) {
      try { return await readFile(pathFor(ref)); }
      catch (e) { if (e.code === "ENOENT") return null; throw e; }
    },
    async remove(ref) {
      try { await unlink(pathFor(ref)); return true; }
      catch (e) { if (e.code === "ENOENT") return false; throw e; }
    },
  };
}

function r2Store({ endpoint, bucket, accessKeyId, secretAccessKey }) {
  let signer;
  const base = `${endpoint.replace(/\/$/, "")}/${bucket}`;
  async function sign() {
    if (!signer) {
      const { AwsClient } = await import("aws4fetch");
      signer = new AwsClient({ accessKeyId, secretAccessKey, service: "s3", region: "auto" });
    }
    return signer;
  }
  return {
    name: "r2",
    async put(ref, bytes) {
      const client = await sign();
      const res = await client.fetch(`${base}/${ref}`, {
        method: "PUT", body: bytes,
        headers: { "content-type": "application/octet-stream", "content-length": String(bytes.length) },
      });
      if (!res.ok) throw new Error(`object store rejected the upload (${res.status})`);
      return { ref, bytes: bytes.length };
    },
    async get(ref) {
      const client = await sign();
      const res = await client.fetch(`${base}/${ref}`);
      if (res.status === 404) return null;
      if (!res.ok) throw new Error(`object store read failed (${res.status})`);
      return Buffer.from(await res.arrayBuffer());
    },
    async remove(ref) {
      const client = await sign();
      const res = await client.fetch(`${base}/${ref}`, { method: "DELETE" });
      return res.ok || res.status === 404;
    },
  };
}

export function chooseStore(config) {
  if (config.storage.driver === "s3") {
    const { endpoint, bucket, accessKeyId, secretAccessKey } = config.storage;
    if (!endpoint || !bucket || !accessKeyId || !secretAccessKey) {
      throw new Error("STORAGE_DRIVER=s3 needs S3_ENDPOINT, S3_BUCKET, S3_ACCESS_KEY_ID and S3_SECRET_ACCESS_KEY");
    }
    return r2Store(config.storage);
  }
  return localStore({ dir: config.storage.uploadDir });
}

export { localStore, r2Store };
